core/urls.py
from django.urls import path
from .views import ItemDetailView, \
    add_to_cart, \
    remove_from_cart, \
    OrderSummaryView, \
    remove_single_item_from_cart, \
    CheckoutView, \
    PaymentView, \
    SalesListView, \
    FaqView, \
    get_items_by_rubric, \
    ContactView, \
    PaymentDeliveryView, \
    AddCouponView


app_name = 'core'

urlpatterns = [
    path('product/<slug>', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-single-item-from-cart/<slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('sales/', SalesListView.as_view(), name='sales'),
    path('faq/', FaqView.as_view(), name='questions'),
    path('<str:category>', get_items_by_rubric, name='items-by-category'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('payment_and_delivery/', PaymentDeliveryView.as_view(), name='payment_and_delivery')

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.views import HomeView, CheckoutView
from accounts.views import logout, login, signup
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('core/', include('core.urls'), name='core'),
    path('news/', include('news.urls'), name='news'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

COLOUR_CHOICES = (
    ('BL', 'Black'),
    ('BW', 'Brown'),
    ('Gy', 'Gray'),
    ('Y', 'Yellow'),
    ('R', 'Red'),
    ('O', 'Orange'),
    ('B', 'Blue'),
    ('G', 'Grin')
)


class ItemCategory(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category


class Item(models.Model):
    '''
    This is model that represent our item in the shop
    '''
    title = models.CharField(max_length=100)
    price = models.FloatField()
    length = models.FloatField(default=0)
    weight = models.FloatField(default=0)
    colour = models.CharField(max_length=2, choices=COLOUR_CHOICES, default='BL')
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(ItemCategory,
                                 on_delete=models.CASCADE, default=None)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='media/items', default='media/news/Camping.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product', kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def get_by_category_url(self):
        return reverse('core:items-by-category', kwargs={
            'category': self.category
        })


class ItemImage(models.Model):
    item = models.ForeignKey(Item, related_name='item',
                             on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='media/items', default='media/news/Camping.jpg')


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,
                             on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_data = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        total -= self.coupon.amount
        return total

    def get_total_saved(self):
        total = 0
        for order_item in self.items.all():
            if order_item.item.discount_price:
                total += order_item.get_amount_saved()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

core/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Item, OrderItem, Order, BillingAddress, ItemImage, Payment, Coupon
from django.views.generic import ListView, DetailView, View, TemplateView
from django.utils import timezone
from .forms import CheckoutForm, ContactForm, CouponForm
from django.core.mail import send_mail
from myshop import settings
from .filters import ItemFilter
from django.conf import settings

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


class CheckoutView(View):

    def get(self, *args, **kwargs):
        try:
            form = CheckoutForm()
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'form': form,
                'couponform': CouponForm(),
                'DISPLAY_COUPON_FORM': True,
                'order': order
            }
            return render(self.request, 'core/checkout-page.html', context)
        except ObjectDoesNotExist:
            messages.info(self.request, 'You do not have an active order')
            return redirect('core:checkout')

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                #TODO: add functionality for these fields
                #same_shipping_address = form.cleaned_data.get(
                #    'same_shipping_address')
                #save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip=zip
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                if payment_option == 'S':
                    return redirect('core:payment', payment_option=stripe)
                elif payment_option == 'P':
                    return redirect('core:payment', payment_option='paypal')
                else:
                    messages.warning(self.request, 'The invalid payment option was selected!')
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "You don't have an active order!")
            return redirect('core:order-summary')


class PaymentView(View):

    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'DISPLAY_COUPON_FORM': False
            }
            return render(self.request, 'core/payment.html', context)
        else:
            messages.warning(self.request, "You have not added a billing address")
            return redirect('core:checkout')

    def post(self, *args, **kwargs):
        #TODO: fix this method, make it display messages and check if it works properly
        payment_option = 'stripe'
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        amount = int(order.get_total() * 100)  # cents
        messages.warning = messages.error
        try:
            charge = stripe.Charge.create(
                amount=amount,  #cents
                currency="usd",
                source=token,
        )
            # create the payment
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = order.get_total()
            payment.save()

            # assign the payment to the order

            order_items = order.items.all()
            order_items.update(ordered=True)
            for item in order_items:
                item.save()

            order.ordered = True
            order.payment = payment
            order.save()
            messages.info(self.request, 'The charge was successful!')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.CardError as e:
            body = e.json_body
            err = body.get('error', {})
            messages.warning(self.request, f'{err.get("message")}')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.RateLimitError as e:
            # Too many requests made to the API too quickly
            messages.warning(self.request, 'Rate limit error')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.InvalidRequestError as e:
            # Invalid parameters were supplied to Stripe's API
            messages.warning(self.request, 'Invalid parameters')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.AuthenticationError as e:
            # Authentication with Stripe's API failed
            # (maybe you changed API keys recently)
            messages.warning(self.request, 'Not authenticated')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.APIConnectionError as e:
            # Network communication with Stripe failed
            messages.warning(self.request, 'Network error')
            return redirect('core:payment', payment_option=payment_option)

        except stripe.error.StripeError as e:
            # Display a very generic error to the user, and maybe send
            # yourself an email
            messages.warning(self.request, 'Something went wrong.'
                                         'You were not charged. Please try again.')
            return redirect('core:payment', payment_option=payment_option)

        except Exception as e:
            messages.warning(self.request, 'A serious error occurred. We have been notified.')
            return redirect('core:payment', payment_option=payment_option)


class HomeView(ListView):
    model = Item
    paginate_by = 6  # the number of items shown on the homepage
    template_name = 'core/home-page.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        item = Item.objects.all()
        myfilter = ItemFilter(self.request.GET, queryset=item)
        items = myfilter.qs
        context['images'] = ItemImage.objects.all()
        context['filter'] = myfilter
        context['items'] = items
        return context


def get_items_by_rubric(request, category):
    object_list = Item.objects.filter(category=category)
    categories = Item.objects.order_by().values('category').distinct()
    #TODO: solve the problem of getting rid of all categories on template
    context = {
        'object_list': object_list,
        'categories': categories
    }
    return render(request, 'core/home-page.html', context=context)


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'core/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You don't have an active order!")
            return redirect('/')


class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/product-page.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['images'] = ItemImage.objects.all()
        return context


def product_page(request):
    return render(request, 'core/product-page.html')


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'This item quantity was updated. ')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'This item was added to your cart. ')
            order.items.add(order_item)
            return redirect('core:order-summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_data=ordered_date)
        order.items.add(order_item)
        messages.info(request, 'This item was added to your cart. ')
        return redirect('core:order-summary')


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load cart_template_tags %}
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>FFish</title>
  {% block extra_head %}

  {% endblock extra_head %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">


      <a class="navbar-brand waves-effect" href="{% url 'home' %}">
        <strong class="blue-text"> FirstFish </strong>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'all_newses' %}" > News </a>
            <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %}"> Checkout </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:sales' %}" > Sales </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:payment_and_delivery' %}" > Payment and delivery </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:contacts' %}"> Contacts </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:questions' %}"> Help </a>
          </li>
          <!-- TODO: fix this form, make it display -->
          <li class="nav-item">
          <a href="" class="nav-link waves-effect" data-toggle="modal" data-target="#myModal">
            Modal Contact Form</a>
          </li>


        </ul>
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href=" {% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user| cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Sign Up </span>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>
    <div>
        {% block content %}


        {% endblock %}
    </div>

<!-- Modal Form -->
<!-- TODO: fix this form, make it display -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header text-center">
          <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body mx-3">
          <div class="md-form mb-5">
            <i class="fas fa-user prefix grey-text"></i>
            <input type="text" id="form34" class="form-control validate">
            <label data-error="wrong" data-success="right" for="form34">Your name</label>
          </div>

          <div class="md-form mb-5">
            <i class="fas fa-envelope prefix grey-text"></i>
            <input type="email" id="form29" class="form-control validate">
            <label data-error="wrong" data-success="right" for="form29">Your email</label>
          </div>

          <div class="md-form mb-5">
            <i class="fas fa-tag prefix grey-text"></i>
            <input type="text" id="form32" class="form-control validate">
            <label data-error="wrong" data-success="right" for="form32">Subject</label>
          </div>

          <div class="md-form">
            <i class="fas fa-pencil prefix grey-text"></i>
            <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
            <label data-error="wrong" data-success="right" for="form8">Your message</label>
          </div>

        </div>
        <div class="modal-footer d-flex justify-content-center">
          <button class="btn btn-unique">Send <i class="fas fa-paper-plane-o ml-1"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="page-footer font-small blue pt-4">
  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text">FirstFish</h5>
        <p>Our schedule:</p>
        <p>Monday - Saturday</p>
        <p>From 8 a.m. to 6 p.m.</p>
        <p>You can phone us: </p>
        <p>+380993563938</p>

      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Information</h5>
        <ul class="list-unstyled">
          <li>
            <a href="{% url 'all_newses' %}">News</a>
          </li>
          <li>
            <a href="{% url 'core:sales' %}">Sales</a>
          </li>
          <li>
            <a href="{% url 'core:payment_and_delivery' %}">Payment and Delivery</a>
          </li>
          <li>
            <a href="{% url 'core:contacts' %}">Contacts</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">
          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
</footer>


  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

core/templates/core/item_list.html
{% extends 'core/base.html' %}

{% block content %}
<div>
<h2> Here is the list of item: </h2>

    {% for item in items %}

        {{ item.title }}
        {{ item.price }}

    {% endfor %}
</div>
{% endblock %}

core/templates/core/order_snippet.html
<div class="col-md-12 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{order_item.item.title}}</h6>
                <small class="text-muted">{{order_item.item.title}}</small>
              </div>
              <span class="text-muted">${{ order_item.get_final_price }}</span>
            </li>

            {% endfor %}

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
              </div>
              <span class="text-success">-${{ order.coupon.amount }} </span>
            </li>

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ order.get_total }}</strong>
            </li>
          </ul>
                {% if DISPLAY_COUPON_FORM %}
              <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
                  {% csrf_token %}
                <div class="input-group">
                    {{ couponform.code }}
                    <div class="input-group-append">
                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                  </div>
                </div>
              </form>
                {% endif %}

        </div>

core/templates/core/order_summary.html
{% extends 'core/base.html' %}

{% block content %}

  <main>
    <div class="container">
         <div class="table-responsive text-nowrap">
          <table class="table">
            <h2> Order Summary </h2>
            <thead>
              <tr>
                <th scope="col">№</th>
                <th scope="col">Item Title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Item Price</th>
              </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order_item.item.title }}</td>
                <td>
                {% if order_item.item.discount_price %}
                  ${{ order_item.item.discount_price }}
                {% else %}
                  ${{ order_item.item.price }}
                </td>
                {% endif %}
                <td>
                  <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}" ><i class="fas fa-minus mr-2"></i></a>
                  {{ order_item.quantity }}
                  <a href="{% url 'core:add-to-cart' order_item.item.slug %}"> <i class="fas fa-plus ml-2"></i> </a></td>
                <td>
                {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price }}
                  <span class="badge badge-warning">Saving ${{ order_item.get_amount_saved }}</span>
                  {% else %}
                   ${{ order_item.get_total_item_price }}
                  {% endif %}
                  <a style="color: red;" href="{% url 'core:remove-from-cart' order_item.item.slug %}" >
                    <i class="fas fa-trash float-right"></i> </a>
                </td>
              </tr>
              {% empty %}
            <tr>
              <td colspan="5"> Your cart is empty! </td>
            </tr>
            <tr>
                <td colspan="5">
                  <a class="btn btn-primary float-right ml-2" href="/"> Continue Shopping </a>
                </td>
              </tr>
            {% endfor %}
            {% if object.coupon %}
              <tr>
                <td colspan="4"><b> Coupon </b> </td>
                <td><b>${{ object.coupon.amount }} </b> </td>
              </tr>
            {% endif %}

            {% if object.get_total %}
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td> <b> Total </b></td>
                <td>
                  <b> {{ object.get_total }} </b>
                  <span class="badge badge-warning">Saving ${{ object.get_total_saved }}</span>
                </td>
              </tr>
              <tr>
                <td colspan="5">
                  <a class="btn btn-primary float-right ml-2" href="/"> Continue Shopping </a>
                  <a class="btn btn-success float-right" href="{% url 'core:checkout' %}"> Proceed to checkout </a>
                </td>
              </tr>
            {% endif %}
            </tbody>
          </table>
        </div>
    </div>
  </main>
{% endblock %}